### ISSUE TITLE
sql table name order is stricted

### ISSUE THREAD

**Issue by visus100** [visus100/invoice#3]
We should change the names "order "to another couse the value in order is strcited in mysql. propably its for secure maintence in querys example:  
"SELECT * form table ORDER BY id ASC"

It`s for better structures 
for now i am using in sql table named "orders"

**Comment by Mati2906** [comment]
Ok, aprove that Order have to be change. Changed Order to Order_item to leave information about single object

**Comment by visus100** [comment]
it's can'y be named order_item beacouse it's alredy using by other table.

**Comment by Mati2906** [comment]
Changed for Purchase

**Comment by visus100** [comment]
thanks
